services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/springboot3
    volumes:
      - db:/data/springboot3
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    
networks:
  db: 
    driver: bridge
    
volumes:
  db:
    